### ISSUE TITLE
Ошибка The requested resource was not found 

### ISSUE THREAD

**Issue by DBoyara** [FinamWeb/trade-api-docs#12]
При попытки создания стоп-заявки с таким body:
`{'clientId': 'clientId', 'securityBoard': 'FUT', 'securityCode': 'SiH3', 'buySell': 'Sell', 'stopLoss': {'activationPrice': 74850.0, 'marketPrice': True, 'quantity': {'value': 1.0, 'units': 'Lots'}}, 'takeProfit': {'activationPrice': 75100.0, 'marketPrice': True, 'quantity': {'value': 1.0, 'units': 'Lots'}}} `
получаю ошибку 
`code='NOT_FOUND' message='The requested resource was not found' data=None`

Пробовал передавать с `linkOrder` - ошибка сохраняется. При этом обычные заявки создаются корректно. В чем причина?

**Comment by DBoyara** [comment]
стучался в старую апи, всё ок работает

**Comment by Vkhalchenya** [comment]
Добрый день!
Большое спасибо за живой и продуктивный интерес к нашему API. Я являюсь менеджером этого продукта в Финаме и сейчас планирую официальный запуск проекта.
Подскажите, вам было бы интересно созвониться и обсудить возможности расширенного сотрудничества?
